### ISSUE TITLE
how to set guifont

### ISSUE THREAD

**Issue by DemonCloud** [igorgladkoborodov/vv#9] opened 2018-10-13 02:10 UTC
set guifont=* not active

**Comment by DemonCloud** [comment] 2018-10-13 02:17
i find a bug.  if init.vim with source other vim file. VVset in the setting will not work currently

**Comment by igorgladkoborodov** [comment] 2018-10-13 07:32
Yes, set guifont is not working now. You can use `VVset fontfamily` and `VVset fontsize` to set font. Will support guifont in upcoming updates.

Regarding sourced files, that's weird. It does work with sourced files. Does it work if you run `VVset` when VV was started? Please try `:VVset fu` when everything loaded. Will try with your dotfiles tomorrow.

**Comment by igorgladkoborodov** [comment] 2018-10-13 18:47
Checked with your dotfiles and it works for me. Added `~/.aix/.vv.vim` with
```
if exists('g:vv')
  VVset fontsize=24
endif
```

Can you provide a minimum example to reproduce?

**Comment by igorgladkoborodov** [comment] 2018-10-15 01:42
Made `set guifont` work. Closing this for now, please reopen or make separate issue if you still have problems with sourcing config with VVset.

**Closed by igorgladkoborodov** 2018-10-15 01:42 UTC
